site_name: Maksim Solovyov â€“ Portfolio
nav:
  - Home: index.md
  - Projects:
      - SWIFT Message System: projects/electronic_financial_messages.md
      - Message Authentication: projects/financial_message_authentication.md
      - Long-Term Storage: projects/long_term_storage.md

theme:
  name: material